// Code generated by unikraft.com/cloud/pluginsdk/tools/sdkgen. DO NOT EDIT.

package widgets

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/url"

	"unikraft.com/cloud/sdk/platform"
)

// Ensure imports are used: a spec need not exercise every one of them, and a
// spec with no operations at all exercises none.
var (
	_ = bytes.NewReader
	_ context.Context
	_ = json.Marshal
	_ = fmt.Sprintf
	_ io.Reader
	_ = url.Values{}
	_ platform.Instance
)

// CreateWidget
//
// The payload is the Data member of the returned envelope, which is also
// returned on error so its status, message and per-object errors can be read.
//
// It targets the widgets plugin running on the given instance,
// reached through the instance's authenticated plugin endpoint
// (<endpoint>/v1/instances/<uuid>/plugins/<plugin>).
func (c *Client) CreateWidget(ctx context.Context, instance platform.Instance, body *CreateWidgetRequest, opts ...Option) (*Response[CreateWidgetResponseData], error) {
	pathParams := map[string]string{}
	opPath := buildPath("/widgets", pathParams)

	q := url.Values{}
	if len(q) > 0 {
		opPath = opPath + "?" + q.Encode()
	}

	var bodyReader io.Reader
	if body != nil {
		bodyBytes, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal request body: %w", err)
		}
		bodyReader = bytes.NewReader(bodyBytes)
	}

	resp := &Response[CreateWidgetResponseData]{}
	if err := doRequest(ctx, c, instance, "POST", opPath, bodyReader, resp, opts...); err != nil {
		return resp, err
	}
	return resp, nil
}

// DeleteWidget
//
// The payload is the Data member of the returned envelope, which is also
// returned on error so its status, message and per-object errors can be read.
//
// It targets the widgets plugin running on the given instance,
// reached through the instance's authenticated plugin endpoint
// (<endpoint>/v1/instances/<uuid>/plugins/<plugin>).
func (c *Client) DeleteWidget(ctx context.Context, instance platform.Instance, id string, opts ...Option) (*Response[any], error) {
	pathParams := map[string]string{
		"id": fmt.Sprintf("%v", id),
	}
	opPath := buildPath("/widgets/{id}", pathParams)

	q := url.Values{}
	if len(q) > 0 {
		opPath = opPath + "?" + q.Encode()
	}

	var bodyReader io.Reader

	resp := &Response[any]{}
	if err := doRequest(ctx, c, instance, "DELETE", opPath, bodyReader, resp, opts...); err != nil {
		return resp, err
	}
	return resp, nil
}

// GetWidget
//
// The payload is the Data member of the returned envelope, which is also
// returned on error so its status, message and per-object errors can be read.
//
// It targets the widgets plugin running on the given instance,
// reached through the instance's authenticated plugin endpoint
// (<endpoint>/v1/instances/<uuid>/plugins/<plugin>).
func (c *Client) GetWidget(ctx context.Context, instance platform.Instance, id string, opts ...Option) (*Response[GetWidgetResponseData], error) {
	pathParams := map[string]string{
		"id": fmt.Sprintf("%v", id),
	}
	opPath := buildPath("/widgets/{id}", pathParams)

	q := url.Values{}
	if len(q) > 0 {
		opPath = opPath + "?" + q.Encode()
	}

	var bodyReader io.Reader

	resp := &Response[GetWidgetResponseData]{}
	if err := doRequest(ctx, c, instance, "GET", opPath, bodyReader, resp, opts...); err != nil {
		return resp, err
	}
	return resp, nil
}

// ListWidgetsOpts contains optional parameters for ListWidgets.
type ListWidgetsOpts struct {
	Limit *int
}

// ListWidgets
//
// The payload is the Data member of the returned envelope, which is also
// returned on error so its status, message and per-object errors can be read.
//
// It targets the widgets plugin running on the given instance,
// reached through the instance's authenticated plugin endpoint
// (<endpoint>/v1/instances/<uuid>/plugins/<plugin>).
func (c *Client) ListWidgets(ctx context.Context, instance platform.Instance, params *ListWidgetsOpts, opts ...Option) (*Response[ListWidgetsResponseData], error) {
	pathParams := map[string]string{}
	opPath := buildPath("/widgets", pathParams)

	q := url.Values{}
	if params != nil && params.Limit != nil {
		addQueryParam(q, "limit", *params.Limit)
	}
	if len(q) > 0 {
		opPath = opPath + "?" + q.Encode()
	}

	var bodyReader io.Reader

	resp := &Response[ListWidgetsResponseData]{}
	if err := doRequest(ctx, c, instance, "GET", opPath, bodyReader, resp, opts...); err != nil {
		return resp, err
	}
	return resp, nil
}

// WatchWidget
//
// The response is streamed as Server-Sent Events (SSE). The returned channel
// emits decoded frames and is closed when the stream ends or ctx is cancelled.
// A plugin that cannot start the stream answers with a response envelope
// instead, which is returned as the error.
//
// It targets the widgets plugin running on the given instance,
// reached through the instance's authenticated plugin endpoint
// (<endpoint>/v1/instances/<uuid>/plugins/<plugin>).
func (c *Client) WatchWidget(ctx context.Context, instance platform.Instance, id string, opts ...Option) (<-chan *Widget, error) {
	pathParams := map[string]string{
		"id": fmt.Sprintf("%v", id),
	}
	opPath := buildPath("/widgets/{id}/events", pathParams)

	q := url.Values{}
	if len(q) > 0 {
		opPath = opPath + "?" + q.Encode()
	}

	var bodyReader io.Reader

	resp := &Response[Widget]{}
	if err := doStream(ctx, c, instance, "GET", opPath, bodyReader, resp, opts...); err != nil {
		return nil, err
	}
	return resp.Events()
}
