// Code generated by unikraft.com/cloud/pluginsdk/tools/sdkgen. DO NOT EDIT.

package widgets

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime"
	"net/http"
	"os"
	"strings"
	"time"

	"unikraft.com/cloud/sdk/platform"
)

const (
	// Version is the version of this generated SDK.  It is the version the SDK
	// was published as, and is what DefaultUserAgent reports.
	Version = "0.0.0"

	// DefaultUserAgent is the default User-Agent header value.
	DefaultUserAgent = "unikraft-cloud-plugin-widgets/" + Version

	// DefaultTimeout is the default HTTP client timeout.
	DefaultTimeout = 30 * time.Second

	// PluginName is the default name of this plugin as it is mounted on an
	// instance.  It forms the "<plugin_name>" segment of the plugin endpoint
	// path and can be overridden per call with WithPluginName.
	PluginName = "widgets"
)

// tokenEnvVars lists, in order of precedence, the environment variables from
// which a Unikraft Cloud API token is read when no token is supplied
// explicitly.  It mirrors the platform SDK's own precedence.
var tokenEnvVars = []string{
	"UKC_TOKEN",
	"UNIKRAFT_CLOUD_TOKEN",
	"KRAFTCLOUD_TOKEN",
}

// Client is a plugin API client bound to a set of Unikraft Cloud credentials
// and endpoint configuration.  It is constructed with NewClient from the same
// platform.ClientOption values used to build the platform SDK client, so the
// metro (endpoint) and bearer token it carries match the platform client.  Its
// generated operation methods each take the target platform.Instance and reach
// the plugin through the instance's authenticated plugin endpoint
// (<endpoint>/v1/instances/<uuid>/plugins/<plugin>).
type Client struct {
	// endpoint is the API endpoint derived from the supplied options, falling
	// back to the UKC_METRO environment variable and then the default metro.
	endpoint string

	// token is the bearer token used to authenticate plugin requests.
	token string

	// userAgent is the User-Agent header sent with plugin requests.
	userAgent string

	// pluginName is the "<plugin_name>" segment of the plugin endpoint path.
	pluginName string

	// httpClient performs the plugin HTTP requests.
	httpClient *http.Client
}

// NewClient creates a plugin client from the given platform client options,
// the same ones passed to platform.NewClient.  The endpoint (metro) and bearer
// token are taken from those options; when no token is supplied it falls back
// to the UKC_TOKEN, UNIKRAFT_CLOUD_TOKEN and KRAFTCLOUD_TOKEN environment
// variables, mirroring the platform SDK's own precedence.
func NewClient(opts ...platform.ClientOption) *Client {
	copts := &platform.ClientOptions{}
	for _, opt := range opts {
		opt(copts)
	}

	token := copts.Token()
	if token == "" {
		token = tokenFromEnv()
	}

	userAgent := copts.UserAgent()
	if userAgent == "" {
		userAgent = DefaultUserAgent
	}

	// Derive the endpoint from the options, mirroring platform.NewClient: an
	// explicit endpoint/metro from the options, then the UKC_METRO environment
	// variable, and finally the default metro.
	endpoint := copts.DefaultEndpoint()
	if endpoint == "" {
		if metro := os.Getenv("UKC_METRO"); metro != "" {
			endpoint = platform.EndpointForMetro(metro)
		}
	}
	if endpoint == "" {
		endpoint = platform.EndpointForMetro(platform.DefaultMetro)
	}

	return &Client{
		endpoint:   endpoint,
		token:      token,
		userAgent:  userAgent,
		pluginName: PluginName,
		httpClient: &http.Client{Timeout: DefaultTimeout},
	}
}

// Option overrides part of a Client's configuration for a single API call.
type Option func(*options)

// options holds the per-call configuration resolved from the Client's
// configuration and the supplied Options.
type options struct {
	endpoint   string
	metro      string
	token      string
	pluginName string
	userAgent  string
	httpClient *http.Client
	headers    map[string]string
}

// WithEndpoint overrides the API endpoint (e.g. https://api.fra.unikraft.cloud).
func WithEndpoint(endpoint string) Option {
	return func(o *options) { o.endpoint = endpoint }
}

// WithMetro overrides the metro used to derive the API endpoint.
func WithMetro(metro string) Option {
	return func(o *options) { o.metro = metro }
}

// WithToken overrides the bearer token used to authenticate the request.
func WithToken(token string) Option {
	return func(o *options) { o.token = token }
}

// WithPluginName overrides the "<plugin_name>" segment of the endpoint path.
func WithPluginName(name string) Option {
	return func(o *options) { o.pluginName = name }
}

// WithUserAgent sets the User-Agent header.
func WithUserAgent(userAgent string) Option {
	return func(o *options) { o.userAgent = userAgent }
}

// WithHTTPClient sets a custom HTTP client.
func WithHTTPClient(httpClient *http.Client) Option {
	return func(o *options) { o.httpClient = httpClient }
}

// WithHeader sets an additional header to send with the request.
func WithHeader(key, value string) Option {
	return func(o *options) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// tokenFromEnv returns the first non-empty token found in the environment.
func tokenFromEnv() string {
	for _, key := range tokenEnvVars {
		if v := os.Getenv(key); v != "" {
			return v
		}
	}
	return ""
}

// resolve merges the Client's configuration and the per-call Options into a
// concrete per-call configuration, filling in defaults.
func (c *Client) resolve(opts ...Option) options {
	o := options{
		endpoint:   c.endpoint,
		token:      c.token,
		pluginName: c.pluginName,
		userAgent:  c.userAgent,
		httpClient: c.httpClient,
	}
	for _, opt := range opts {
		opt(&o)
	}

	// A per-call metro override takes precedence over the Client's endpoint.
	if o.metro != "" {
		o.endpoint = platform.EndpointForMetro(o.metro)
	}

	if o.pluginName == "" {
		o.pluginName = PluginName
	}
	if o.userAgent == "" {
		o.userAgent = DefaultUserAgent
	}
	if o.httpClient == nil {
		o.httpClient = &http.Client{Timeout: DefaultTimeout}
	}

	return o
}

// newRequest builds the HTTP request for a single plugin API call against the
// instance's authenticated plugin endpoint.
func newRequest(ctx context.Context, o options, instance platform.Instance, method, opPath string, body io.Reader, accept string) (*http.Request, error) {
	if o.endpoint == "" {
		return nil, fmt.Errorf("could not determine the API endpoint: configure a metro or endpoint through NewClient's options, or use WithEndpoint or WithMetro")
	}
	if instance.Uuid == "" {
		return nil, fmt.Errorf("instance has no UUID; cannot address its plugin endpoint")
	}

	base := strings.TrimSuffix(o.endpoint, "/")
	prefix := fmt.Sprintf("/v1/instances/%s/plugins/%s", instance.Uuid, o.pluginName)

	req, err := http.NewRequestWithContext(ctx, method, base+prefix+opPath, body)
	if err != nil {
		return nil, fmt.Errorf("creating the request: %w", err)
	}

	req.Header.Set("User-Agent", o.userAgent)
	req.Header.Set("Accept", accept)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if o.token != "" {
		req.Header.Set("Authorization", "Bearer "+o.token)
	}
	for key, value := range o.headers {
		req.Header.Set(key, value)
	}

	return req, nil
}

// doRequest performs a single plugin API call and hydrates target from the
// JSON envelope the plugin answered with.  target is populated whenever a
// response was received, including on error, so a caller that gets an error
// back can still read the envelope's message, its per-object errors and — on a
// partial success — the data of the objects that did succeed.
//
// The body is read in full and replaced with an equivalent in-memory reader, so
// target.Raw() is still readable from its first byte and needs no Close from the
// caller.  Streaming operations go through doStream instead.
func doRequest[T any](ctx context.Context, c *Client, instance platform.Instance, method, opPath string, body io.Reader, target *Response[T], opts ...Option) error {
	o := c.resolve(opts...)

	req, err := newRequest(ctx, o, instance, method, opPath, body, "application/json")
	if err != nil {
		return err
	}

	resp, err := o.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("performing the request: %w", err)
	}

	raw, err := receive(resp, target)
	if err != nil {
		return err
	}

	return target.hydrate(raw)
}

// doRawRequest performs a plugin API call whose response body is returned
// verbatim rather than enveloped — a file, or a log stream served as
// application/octet-stream.  The body is buffered into target and reachable
// through RawBody and Raw, but never decoded, so a body that is not JSON is not
// an error; target.Data stays nil.  Only the HTTP status is judged.
func doRawRequest[T any](ctx context.Context, c *Client, instance platform.Instance, method, opPath, accept string, body io.Reader, target *Response[T], opts ...Option) error {
	o := c.resolve(opts...)

	req, err := newRequest(ctx, o, instance, method, opPath, body, accept)
	if err != nil {
		return err
	}

	resp, err := o.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("performing the request: %w", err)
	}

	raw, err := receive(resp, target)
	if err != nil {
		return err
	}

	return target.statusErr(raw)
}

// receive buffers the response body into target and returns it.  The body is
// drained — which releases the connection to the transport — and replaced with
// a reader over the bytes that were read, so target.Raw() is still readable in
// full, from its first byte, and needs no Close from the caller.
func receive[T any](resp *http.Response, target *Response[T]) ([]byte, error) {
	target.raw = resp

	raw, err := io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	resp.Body = io.NopCloser(bytes.NewReader(raw))
	target.body.Write(raw)

	if err != nil {
		return raw, fmt.Errorf("reading the response: %w", err)
	}

	return raw, nil
}

// doStream performs a plugin API call that answers with a Server-Sent Events
// stream and wires the stream into target's event channel, which target.Events
// hands to the caller.  The response body stays open until the stream ends or
// ctx is cancelled, and the HTTP client timeout is disabled for the call so the
// stream is not cut short; cancellation is controlled through ctx.
//
// A plugin that cannot start the stream answers with a JSON envelope instead,
// which is decoded into target and returned as an error like any other failed
// call.
func doStream[T any](ctx context.Context, c *Client, instance platform.Instance, method, opPath string, body io.Reader, target *Response[T], opts ...Option) error {
	o := c.resolve(opts...)

	req, err := newRequest(ctx, o, instance, method, opPath, body, "text/event-stream")
	if err != nil {
		return err
	}

	// Clone the HTTP client with no timeout so the stream can stay open.
	httpClient := *o.httpClient
	httpClient.Timeout = 0

	resp, err := httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("performing the request: %w", err)
	}

	mediaType, _, _ := mime.ParseMediaType(resp.Header.Get("Content-Type"))
	if mediaType == "text/event-stream" && resp.StatusCode < 400 {
		target.raw = resp
		target.events = make(chan *T)
		go streamSSE(ctx, resp.Body, target.events)
		return nil
	}

	// Not the stream that was asked for: the body is the envelope describing why.
	raw, err := receive(resp, target)
	if err != nil {
		return err
	}

	if err := target.hydrate(raw); err != nil {
		return err
	}

	return fmt.Errorf("expected a text/event-stream response, got %q", resp.Header.Get("Content-Type"))
}

// hydrate decodes an API response body into the envelope and reports the error
// it describes, joining it with the error the HTTP status code implies.
func (r *Response[T]) hydrate(raw []byte) error {
	// A 204, and any other empty body, carries no envelope to decode.
	if len(bytes.TrimSpace(raw)) == 0 {
		return r.statusErr(raw)
	}

	if err := json.Unmarshal(raw, r); err != nil {
		// Not an envelope: something in front of the plugin — a gateway, a
		// proxy, an authentication layer — answered in a shape of its own.  Its
		// body is still the best account of a failure; a body that merely is not
		// JSON, on an otherwise fine response, is the caller's to read.
		if statusErr := r.statusErr(raw); statusErr != nil {
			return statusErr
		}

		return fmt.Errorf("parsing the response: %w", err)
	}

	if !r.IsSuccess() {
		return errors.Join(r.transportErr(), NewFromResponse(r))
	}

	// A failing status code with a successful — or absent — envelope status
	// still failed; report it with whatever the body said.
	return r.statusErr(raw)
}

// statusErr reports the error a non-2xx status implies, described with whatever
// the body carried.  It is the whole verdict for a response that is not an
// envelope, and the fallback for one whose envelope did not explain itself.
func (r *Response[T]) statusErr(raw []byte) error {
	transportErr := r.transportErr()
	if transportErr == nil {
		return nil
	}

	return errors.Join(transportErr, &APIError{
		StatusCode: r.StatusCode(),
		Message:    messageFromBody(raw),
	})
}

// transportErr reports the bare failure a non-2xx status is, before anything in
// the body is taken into account.
func (r *Response[T]) transportErr() error {
	if code := r.StatusCode(); code >= 200 && code < 300 {
		return nil
	}

	return fmt.Errorf("request failed: %s", r.raw.Status)
}
