// Code generated by unikraft.com/cloud/pluginsdk/tools/sdkgen. DO NOT EDIT.

// Package widgets provides a generated Go client.
//
// Every operation is a method on [Client] that takes the target
// platform.Instance and reaches the plugin through the instance's authenticated
// plugin endpoint.  Operations return the [Response] envelope — the same one the
// Unikraft Cloud platform API returns, and the one the server-side plugin
// framework serves — whose Data member holds the payload; a streaming operation
// returns a channel of decoded frames instead.  A failed call returns both the
// envelope and an [APIError] describing it.
package widgets
