// Code generated by unikraft.com/cloud/pluginsdk/tools/sdkgen. DO NOT EDIT.

package widgets

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"unikraft.com/cloud/sdk/platform"
)

// ErrorResponse is the shape of an error body that is not a plugin envelope.
// A gateway, proxy or authentication layer in front of the plugin can answer
// with one of these instead, so its message is still surfaced.
type ErrorResponse struct {
	// Message is the error message.
	Message string `json:"message,omitempty"`

	// ErrorMsg is the alternative error field used by some APIs.
	ErrorMsg string `json:"error,omitempty"`

	// ErrorDescription is the OAuth-style error field.
	ErrorDescription string `json:"error_description,omitempty"`

	// Code is an optional error code.
	Code string `json:"code,omitempty"`
}

// GetMessage returns the first populated message field of the response.
func (e *ErrorResponse) GetMessage() string {
	if e == nil {
		return ""
	}

	for _, msg := range []string{e.Message, e.ErrorMsg, e.ErrorDescription} {
		if msg != "" {
			return msg
		}
	}

	return ""
}

// APIError is the error a plugin API call returns when the response envelope
// reports a failure, or when the call failed before an envelope was produced.
// It carries the whole verdict: the envelope's status and message, the
// per-object errors it listed, and the HTTP status code that framed it.
type APIError struct {
	// StatusCode is the HTTP status code of the response, or 0 when the request
	// never reached the API.
	StatusCode int

	// Status is the envelope's status member, i.e. `error` or
	// `partial_success`.  It is empty for a body that was not an envelope.
	Status platform.ResponseStatus

	// Message is the envelope's message member, falling back to whatever
	// message the body did carry.
	Message string

	// Errors are the per-object errors the envelope listed.  On a
	// `partial_success` these describe only the objects that failed.
	Errors []platform.ResponseError
}

// NewFromResponse returns the error the given envelope describes, or nil when
// it describes a fully successful operation.
func NewFromResponse[T any](r *Response[T]) error {
	if r == nil {
		return errors.New("no response")
	}
	if r.IsSuccess() {
		return nil
	}

	return &APIError{
		StatusCode: r.StatusCode(),
		Status:     r.Status,
		Message:    r.Message,
		Errors:     r.Errors,
	}
}

// Error implements the error interface.
func (e *APIError) Error() string {
	if e == nil {
		return ""
	}

	var b strings.Builder

	b.WriteString("API error")
	if e.StatusCode != 0 {
		fmt.Fprintf(&b, " (status %d)", e.StatusCode)
	}
	if e.Status != "" && e.Status != platform.ResponseStatusError {
		fmt.Fprintf(&b, " [%s]", e.Status)
	}
	if e.Message != "" {
		b.WriteString(": " + e.Message)
	}

	// The per-object errors only add their status codes; list them when they
	// say something the HTTP status code does not.
	codes := make([]string, 0, len(e.Errors))
	for _, err := range e.Errors {
		if err.Status == 0 || int(err.Status) == e.StatusCode {
			continue
		}
		codes = append(codes, fmt.Sprintf("%d", err.Status))
	}
	if len(codes) > 0 {
		fmt.Fprintf(&b, " (errors: %s)", strings.Join(codes, ", "))
	}

	return b.String()
}

// IsNotFound returns true if the error is a 404 Not Found error.
func (e *APIError) IsNotFound() bool {
	return e.hasStatus(http.StatusNotFound)
}

// IsBadRequest returns true if the error is a 400 Bad Request error.
func (e *APIError) IsBadRequest() bool {
	return e.hasStatus(http.StatusBadRequest)
}

// IsUnauthorized returns true if the error is a 401 Unauthorized error.
func (e *APIError) IsUnauthorized() bool {
	return e.hasStatus(http.StatusUnauthorized)
}

// IsForbidden returns true if the error is a 403 Forbidden error.
func (e *APIError) IsForbidden() bool {
	return e.hasStatus(http.StatusForbidden)
}

// IsConflict returns true if the error is a 409 Conflict error.
func (e *APIError) IsConflict() bool {
	return e.hasStatus(http.StatusConflict)
}

// IsServerError returns true if the error is a 5xx server error.
func (e *APIError) IsServerError() bool {
	if e == nil {
		return false
	}
	if e.StatusCode >= 500 {
		return true
	}

	for _, err := range e.Errors {
		if err.Status >= 500 {
			return true
		}
	}

	return false
}

// IsPartialSuccess reports whether only some of the objects the operation
// addressed failed.  The response's Data still holds the ones that succeeded.
func (e *APIError) IsPartialSuccess() bool {
	return e != nil && e.Status == platform.ResponseStatusPartialSuccess
}

// hasStatus reports whether the HTTP status code, or any of the envelope's
// per-object errors, is the given code.
func (e *APIError) hasStatus(code int) bool {
	if e == nil {
		return false
	}
	if e.StatusCode == code {
		return true
	}

	for _, err := range e.Errors {
		if int(err.Status) == code {
			return true
		}
	}

	return false
}

// IsAPIError checks whether err is, or wraps, an *APIError.
func IsAPIError(err error) bool {
	var apiErr *APIError
	return errors.As(err, &apiErr)
}

// GetAPIError returns the *APIError err is, or wraps.
func GetAPIError(err error) (*APIError, bool) {
	var apiErr *APIError
	ok := errors.As(err, &apiErr)
	return apiErr, ok
}

// ErrorContains reports whether err is an *APIError that was framed by, or
// listed, the given HTTP status code.
func ErrorContains(err error, code int) bool {
	apiErr, ok := GetAPIError(err)
	if !ok {
		return false
	}

	return apiErr.hasStatus(code)
}

// messageFromBody extracts a human-readable message from a response body that
// is not a plugin envelope, falling back to the body itself.
func messageFromBody(body []byte) string {
	var errResp ErrorResponse
	if json.Unmarshal(body, &errResp) == nil {
		if msg := errResp.GetMessage(); msg != "" {
			return msg
		}
	}

	return strings.TrimSpace(string(body))
}
