// Code generated by unikraft.com/cloud/pluginsdk/tools/sdkgen. DO NOT EDIT.

package widgets

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"strconv"
	"strings"
	"time"
)

// streamSSE reads Server-Sent Events from r and emits each decoded event on
// out.  It follows the SSE event-stream parsing rules: lines are grouped into
// events delimited by a blank line, an event may carry several "data:" fields
// that are concatenated with a newline, and comment lines (starting with ':'),
// such as keepalives, are ignored and never surface as events.  Any other field
// (event/id/retry) is ignored.  Both out and r are closed when the stream ends,
// an unrecoverable read error occurs, or ctx is cancelled.  Cancelling ctx also
// aborts the underlying response body read, terminating the stream.
//
// It is meant to be run in its own goroutine, feeding the channel a Response
// hands out through its Events method.
func streamSSE[T any](ctx context.Context, r io.ReadCloser, out chan<- *T) {
	defer close(out)
	defer func() {
		_ = r.Close()
	}()

	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 10*1024*1024)

	// data accumulates the "data:" field values of the event currently being
	// parsed; per the SSE spec they are joined with "\n" when the event is
	// dispatched on the terminating blank line.
	var data []string

	// dispatch decodes the buffered data fields into a T and sends it,
	// returning false if ctx was cancelled (the caller should stop).
	dispatch := func() bool {
		if len(data) == 0 {
			return true
		}
		payload := strings.Join(data, "\n")
		data = data[:0]

		var event T
		if err := json.Unmarshal([]byte(payload), &event); err != nil {
			// Skip malformed events but keep consuming the stream.
			return true
		}

		select {
		case out <- &event:
			return true
		case <-ctx.Done():
			return false
		}
	}

	for scanner.Scan() {
		line := scanner.Text()

		// A blank line terminates the current event and dispatches it.
		if line == "" {
			if !dispatch() {
				return
			}
			continue
		}

		// Comment/keepalive lines are ignored.
		if strings.HasPrefix(line, ":") {
			continue
		}

		value, ok := strings.CutPrefix(line, "data:")
		if !ok {
			// Ignore other SSE fields (event, id, retry).
			continue
		}
		// Strip a single optional leading space after the colon, per spec.
		value = strings.TrimPrefix(value, " ")
		data = append(data, value)
	}

	// Flush a trailing event that was not terminated by a blank line.
	dispatch()
}

// addQueryParam adds a query parameter to the URL if the value is not nil/empty.
func addQueryParam(q url.Values, name string, value any) {
	if value == nil {
		return
	}

	switch v := value.(type) {
	case string:
		if v != "" {
			q.Set(name, v)
		}
	case *string:
		if v != nil && *v != "" {
			q.Set(name, *v)
		}
	case int:
		q.Set(name, strconv.Itoa(v))
	case *int:
		if v != nil {
			q.Set(name, strconv.Itoa(*v))
		}
	case int64:
		q.Set(name, strconv.FormatInt(v, 10))
	case *int64:
		if v != nil {
			q.Set(name, strconv.FormatInt(*v, 10))
		}
	case float64:
		q.Set(name, strconv.FormatFloat(v, 'f', -1, 64))
	case *float64:
		if v != nil {
			q.Set(name, strconv.FormatFloat(*v, 'f', -1, 64))
		}
	case bool:
		q.Set(name, strconv.FormatBool(v))
	case *bool:
		if v != nil {
			q.Set(name, strconv.FormatBool(*v))
		}
	case []string:
		for _, item := range v {
			q.Add(name, item)
		}
	case time.Time:
		q.Set(name, v.Format(time.RFC3339))
	case *time.Time:
		if v != nil {
			q.Set(name, v.Format(time.RFC3339))
		}
	default:
		// For complex types, try JSON encoding
		if data, err := json.Marshal(v); err == nil {
			q.Set(name, string(data))
		}
	}
}

// buildPath builds a path with path parameters replaced.
func buildPath(pathTemplate string, params map[string]string) string {
	path := pathTemplate
	for key, value := range params {
		path = strings.ReplaceAll(path, "{"+key+"}", url.PathEscape(value))
	}
	return path
}

// formatHeaderValue formats a value for use in an HTTP header.
func formatHeaderValue(v any) string {
	switch val := v.(type) {
	case string:
		return val
	case *string:
		if val != nil {
			return *val
		}
		return ""
	case int:
		return strconv.Itoa(val)
	case *int:
		if val != nil {
			return strconv.Itoa(*val)
		}
		return ""
	case int64:
		return strconv.FormatInt(val, 10)
	case *int64:
		if val != nil {
			return strconv.FormatInt(*val, 10)
		}
		return ""
	case bool:
		return strconv.FormatBool(val)
	case *bool:
		if val != nil {
			return strconv.FormatBool(*val)
		}
		return ""
	default:
		return fmt.Sprintf("%v", v)
	}
}
