// Code generated by unikraft.com/x/tools/openapi-gen. DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"

	"unikraft.com/cloud/sdk/platform"
	"unikraft.com/x/log"
)

// Ensure imports are used.
var (
	_ = bytes.NewReader
	_ = fmt.Sprintf
	_ = json.Marshal
	_ io.Reader
	_ http.Client
	_ context.Context
	_ = log.New
	_ = time.Now
)

// Example provides the API handlers.
type Example interface {
	// Greet the world.
	Greet(g *gin.Context) (*platform.Response[ExampleResponseData], int, error)
	// Greet someone by name.
	GreetWho(g *gin.Context, who string) (*platform.Response[ExampleResponseData], int, error)
}

type ExampleHandler struct {
	service Example
	resp    func(*gin.Context, int, any)
}

// RegisterExample registers the HTTP handlers for the Example service.
func RegisterExample(engine gin.IRouter, service Example, resp func(*gin.Context, int, any), middleware ...gin.HandlerFunc) {
	handler := &ExampleHandler{
		service: service,
		resp:    resp,
	}

	group := engine.Group("", middleware...)
	group.Handle("GET", "/", handler.greet)
	group.Handle("GET", "/:who", handler.greetWho)
}

func (handler *ExampleHandler) greet(g *gin.Context) {
	now := time.Now()
	resp, code, err := handler.service.Greet(g)
	if resp != nil {
		resp.OpTimeUs = uint64(time.Since(now).Microseconds())
	}
	if err != nil {
		if handler.resp != nil {
			handler.resp(g, code, err)
		} else {
			g.JSON(code, platform.Response[any]{
				Status:   platform.ResponseStatusError,
				Message:  err.Error(),
				Errors:   []platform.ResponseError{{Status: uint64(code)}},
				OpTimeUs: uint64(time.Since(now).Microseconds()),
			})
		}
	} else if handler.resp != nil {
		handler.resp(g, code, resp)
	} else {
		g.JSON(code, resp)
	}
}

func (handler *ExampleHandler) greetWho(g *gin.Context) {
	now := time.Now()

	var params struct {
		Who string `uri:"who"`
	}
	if err := g.ShouldBindUri(&params); err != nil {
		log.G(g.Request.Context()).
			Warn().
			Err(err).
			Msg("failed to bind request body")
		if handler.resp != nil {
			handler.resp(g, http.StatusBadRequest, err)
		} else {
			g.JSON(http.StatusBadRequest, platform.Response[any]{
				Status:   platform.ResponseStatusError,
				Message:  err.Error(),
				Errors:   []platform.ResponseError{{Status: http.StatusBadRequest}},
				OpTimeUs: uint64(time.Since(now).Microseconds()),
			})
		}
		return
	}
	resp, code, err := handler.service.GreetWho(g, params.Who)
	if resp != nil {
		resp.OpTimeUs = uint64(time.Since(now).Microseconds())
	}
	if err != nil {
		if handler.resp != nil {
			handler.resp(g, code, err)
		} else {
			g.JSON(code, platform.Response[any]{
				Status:   platform.ResponseStatusError,
				Message:  err.Error(),
				Errors:   []platform.ResponseError{{Status: uint64(code)}},
				OpTimeUs: uint64(time.Since(now).Microseconds()),
			})
		}
	} else if handler.resp != nil {
		handler.resp(g, code, resp)
	} else {
		g.JSON(code, resp)
	}
}
