// Code generated by unikraft.com/x/tools/openapi-gen. DO NOT EDIT.

package api

import (
	"encoding/json/jsontext"
	json "encoding/json/v2"
	"time"
)

// Ensure imports are used.
var (
	_ time.Time
)

// Response containing greeting details.
type ExampleResponse struct {
	// The status of the response.
	Status ResponseStatus `json:"status" yaml:"status"`
	// An optional message providing additional information about the status.
	Message *string `json:"message,omitzero" yaml:"message,omitempty"`
	// The response data for this request.
	Data *ExampleResponseData `json:"data,omitzero" yaml:"data,omitempty"`
	// A list of errors which may have occurred during the request.
	Errors []ResponseError `json:"errors,omitzero" yaml:"errors,omitempty"`
	// The operation time in microseconds.
	OpTimeUs uint64 `json:"op_time_us" yaml:"op_time_us"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *ExampleResponse) UnmarshalJSON(data []byte) error {
	type Alias ExampleResponse
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m ExampleResponse) MarshalJSON() ([]byte, error) {
	type Alias ExampleResponse
	return json.Marshal((Alias)(m))
}

type ExampleResponseData struct {
	Message string `json:"message" yaml:"message"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *ExampleResponseData) UnmarshalJSON(data []byte) error {
	type Alias ExampleResponseData
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m ExampleResponseData) MarshalJSON() ([]byte, error) {
	type Alias ExampleResponseData
	return json.Marshal((Alias)(m))
}

// The error response message for an API request.
type ResponseError struct {
	// The HTTP status code of the error.
	Status uint64 `json:"status" yaml:"status"`

	// AdditionalProperties captures any JSON object members that do not map to
	// an explicit field above.
	AdditionalProperties map[string]jsontext.Value `json:",embed" yaml:"-"`
}

// UnmarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is populated with any unknown object members.
func (m *ResponseError) UnmarshalJSON(data []byte) error {
	type Alias ResponseError
	return json.Unmarshal(data, (*Alias)(m))
}

// MarshalJSON delegates to encoding/json/v2 so that AdditionalProperties
// (tagged `json:",embed"`) is flattened into the parent JSON object.
func (m ResponseError) MarshalJSON() ([]byte, error) {
	type Alias ResponseError
	return json.Marshal((Alias)(m))
}

// The response status of an API request.
type ResponseStatus string

const (
	ResponseStatusSuccess        ResponseStatus = "success"
	ResponseStatusError          ResponseStatus = "error"
	ResponseStatusPartialSuccess ResponseStatus = "partial_success"
)

// Values returns a slice of strings that represents all the possible values of
// the ResponseStatus enum.
func (ResponseStatus) Values() []ResponseStatus {
	return []ResponseStatus{
		ResponseStatusSuccess,
		ResponseStatusError,
		ResponseStatusPartialSuccess,
	}
}

// String returns the ResponseStatus as a string.
func (e ResponseStatus) String() string {
	return string(e)
}
