name: check-pr

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [prod-staging]

jobs:
  check-pr:
    uses: unikraft-cloud/x/.github/workflows/check-pr.yaml@prod-staging
